version: '3.7'
services:

  db:
    image: "postgres:12.2"
    volumes:
      - type: volume
        source: selvrapportering-local-db
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "selvrapportering"

  web:
    image: selvrapportering
    depends_on:
      - db
    ports:
      - "6789:8080"
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/selvrapportering"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"

  # SQL admin
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8079:8080"

volumes:
  selvrapportering-local-db:
